name: Skinner
main: it.tigierrei.skinner.Skinner
version: 3.3.0
softdepend: [MythicMobs,Citizens]
depend: [LibsDisguises,Holograms]
commands:
  skinner:
    description: Use /sk help to see list of commands
    aliases:
      - sk
      - sk1
permissions:
  skinner.*:
    children:
      - skinner.upload
      - skinner.help
      - skinner.skin
      - skinner.reload
    default: op
  skinner.help:
    default: true
  skinner.upload:
    default: op
  skinner.reload:
    default: op
  skinner.skin:
    default: op