name: Skinner
main: it.tigierrei.skinner.Skinner
version: @VERSION@
api-version: 1.13
softdepend: [MythicMobs, Citizens]
depend: [LibsDisguises]
commands:
  skinner:
    description: Use /sk help to see list of commands
    aliases:
      - sk
permissions:
  skinner.*:
    children:
      - skinner.uploadByFile
      - skinner.uploadByUrl
      - skinner.uploadByUsername
      - skinner.uploadByUUID
      - skinner.help
      - skinner.skin
      - skinner.reload
    default: op
  skinner.help:
    default: true
  skinner.uploadByFile:
    default: op
  skinner.uploadByUrl:
    default: op
  skinner.uploadByUsername:
    default: op
  skinner.uploadByUUID:
    default: op
  skinner.reload:
    default: op
  skinner.skin:
    default: op
