name: Skinner
main: it.tigierrei.skinner.Skinner
version: 3.0.1
softdepend: [MythicMobs,Citizens]
depend: [LibsDisguises,Holograms]
commands:
  skinner:
    description: Use /sk help to see list of commands
    aliases:
      - sk
permissions:
  skinner:
    default: op