name: Skinner
main: it.tigierrei.skinner.Skinner
version: 3.1.1
softdepend: [MythicMobs,Citizens]
depend: [LibsDisguises,Holograms]
commands:
  skinner:
    description: Use /sk help to see list of commands
    aliases:
      - sk
      - sk1
permissions:
  skinner:
    default: op